import {
  BuyMeACoffeeIcon,
  DiscordIcon,
  DonatelloIcon,
  FacebookIcon,
  InstagramIcon,
  MonobankIcon,
  TelegramIcon,
  TikTokIcon,
  XIcon,
} from '@/components/icons'
import {
  AgeRestriction,
  LinkType,
  TranslationStatus,
  WorkStatus,
  WorkType,
} from '@/generated/prisma/enums'

import { Globe } from 'lucide-react'

type LinkMeta = {
  label: string
  icon: React.FC<React.SVGProps<SVGSVGElement>>
  tone: string
  toneDark?: string
}

export const WORK_TYPE_LABELS: Record<WorkType, string> = {
  [WorkType.MANGA]: 'Манга',
  [WorkType.MANHWA]: 'Манхва',
  [WorkType.MANHUA]: 'Маньхва',
  [WorkType.MALOPUS]: 'Мальопис',
  [WorkType.COMIC]: 'Комікс',
  [WorkType.WEBCOMIC]: 'Вебкомікс',
}

export const WORK_STATUS_LABELS: Record<WorkStatus, string> = {
  [WorkStatus.ONGOING]: 'Видається',
  [WorkStatus.ENDED]: 'Закінчено',
  [WorkStatus.PAUSED]: 'Призупинено',
  [WorkStatus.LICENSED]: 'Ліцензовано',
  [WorkStatus.ANNOUNCEMENT]: 'Анонсовано',
}

export const TRANSLATION_STATUS_LABELS: Record<TranslationStatus, string> = {
  [TranslationStatus.ONGOING]: 'Перекладається',
  [TranslationStatus.ENDED]: 'Закінчено',
  [TranslationStatus.FREEZED]: 'Призупинено',
  [TranslationStatus.DROPPED]: 'Не перекладається',
}

export const AGE_RESTRICTION_LABELS: Record<AgeRestriction, string> = {
  [AgeRestriction.NO_RESTRICTION]: 'Для всіх',
  [AgeRestriction.SIX_PLUS]: '6+',
  [AgeRestriction.TWELVE_PLUS]: '12+',
  [AgeRestriction.SIXTEEN_PLUS]: '16+',
  [AgeRestriction.EIGHTEEN_PLUS]: '18+',
}

export const LINK_META: Record<LinkType, LinkMeta> = {
  DISCORD: {
    label: 'Discord',
    icon: DiscordIcon,
    tone: '#92c0ff85',
    toneDark: '#2533468a',
  },
  INSTAGRAM: { label: 'Instagram', icon: InstagramIcon, tone: '#c72bb32b' },
  TELEGRAM: { label: 'Telegram', icon: TelegramIcon, tone: '#6298ff29' },
  TIKTOK: { label: 'TikTok', icon: TikTokIcon, tone: '#99434a4d' },
  FACEBOOK: { label: 'Facebook', icon: FacebookIcon, tone: '#4f6fac36' },
  X: {
    label: 'X / Twitter',
    icon: XIcon,
    tone: '#01010136',
    toneDark: '#4e4e4e36',
  },
  MONOBANK: { label: 'monobank', icon: MonobankIcon, tone: '#30343c54' },
  BUYMEACOFFEE: {
    label: 'Buy me a coffee',
    icon: BuyMeACoffeeIcon,
    tone: '#ffe8564d',
    toneDark: '#f7d81526',
  },
  DONATELLO: {
    label: 'Donatello',
    icon: DonatelloIcon,
    tone: '#4a6b9945',
  },
  SITE: {
    label: 'Сайт',
    icon: Globe,
    tone: '#c3c3c34d',
    toneDark: '#c3c3c31f',
  },
}

export const GENRES = [
  { name: 'Бойові мистецтва' },
  { name: 'Гарем' },
  { name: 'Гендерна інтрига' },
  { name: 'Героїчне фентезі' },
  { name: 'Детектив' },
  { name: 'Джьосей' },
  { name: 'Доджінші' },
  { name: 'Драма' },
  { name: 'Екшн' },
  { name: 'Елементи гумору' },
  { name: 'Еччі' },
  { name: 'Жахи' },
  { name: 'Історія' },
  { name: 'Кіберпанк' },
  { name: 'Кодомо' },
  { name: 'Комедія' },
  { name: 'Махо-шьоджьо' },
  { name: 'Меха' },
  { name: 'Містика' },
  { name: 'Мурім' },
  { name: 'Надприродне' },
  { name: 'Наукова фантастика' },
  { name: 'Повсякденність' },
  { name: 'Постапокаліптика' },
  { name: 'Пригоди' },
  { name: 'Психологія' },
  { name: 'Романтика' },
  { name: 'Сейнен' },
  { name: 'Спорт' },
  { name: 'Студенти' },
  { name: 'Трагедія' },
  { name: 'Трилер' },
  { name: 'Фантастика' },
  { name: 'Фентезі' },
  { name: 'Школярі' },
  { name: 'Шьоджьо' },
  { name: 'Шьоджьо-ай' },
  { name: 'Шьонен' },
  { name: 'Шьонен-ай' },
  { name: 'Юрі' },
  { name: 'Яой' },
]

export const TAGS = [
  { name: 'Азартні ігри' },
  { name: 'Алхімія' },
  { name: 'Амнезія / Втрата пам’яті' },
  { name: 'Ангели' },
  { name: 'Антигерой' },
  { name: 'Антиутопія' },
  { name: 'Апокаліпсис' },
  { name: 'Армія' },
  { name: 'Артефакти' },
  { name: 'Боги' },
  { name: 'Бої на мечах' },
  { name: 'Боротьба за владу' },
  { name: 'Брат і сестра' },
  { name: 'Вестерн' },
  { name: 'Виживання' },
  { name: 'Відьма' },
  { name: 'Відеоігри' },
  { name: 'Війна' },
  { name: 'Військові' },
  { name: 'Вікторіанська епоха' },
  { name: 'Віртуальна реальність' },
  { name: 'Вчитель' },
  { name: 'Вогнепальна зброя' },
  { name: 'Володар демонів' },
  { name: 'ГГ — жінка' },
  { name: 'ГГ — імба' },
  { name: 'ГГ — Мері Сью' },
  { name: 'ГГ — чоловік' },
  { name: 'Геймери' },
  { name: 'Гільдії' },
  { name: 'Гобліни' },
  { name: 'Ґуро' },
  { name: 'Ґяру' },
  { name: 'Демони' },
  { name: 'Дракони' },
  { name: 'Дружба' },
  { name: 'Дурний ГГ' },
  { name: 'Ельфи' },
  { name: 'Жорстокий світ' },
  { name: 'Завоювання світу' },
  { name: 'Залякування' },
  { name: 'Звіролюди' },
  { name: 'Згенеровано ШІ' },
  { name: 'Зворотний гарем' },
  { name: 'Злі духи' },
  { name: 'Злочинці / Кримінал' },
  { name: 'Зомбі' },
  { name: 'Ігрові елементи' },
  { name: 'Імперії' },
  { name: 'Історичні' },
  { name: 'Камера' },
  { name: 'Квести' },
  { name: 'Космос' },
  { name: 'Кулінарія' },
  { name: 'Культивація' },
  { name: 'Легендарна зброя' },
  { name: 'Лицарі' },
  { name: 'Лолі' },
  { name: 'Магічна академія' },
  { name: 'Магічні істоти' },
  { name: 'Магія' },
  { name: 'Майбутнє' },
  { name: 'Мафія' },
  { name: 'Медицина' },
  { name: 'Монстри' },
  { name: 'Монстродівчата' },
  { name: 'Навички / здібності' },
  { name: 'Найманці' },
  { name: 'Насильство / жорстокість' },
  { name: 'Нежить' },
  { name: 'Нінджя' },
  { name: 'Обмін тілами' },
  { name: 'Офісні працівники' },
  { name: 'Пародія' },
  { name: 'Підземелля' },
  { name: 'Пірати' },
  { name: 'Подорож у часі' },
  { name: 'Покоївки' },
  { name: 'Політика' },
  { name: 'Поліція' },
  { name: 'Помста' },
  { name: 'Порятунок світу' },
  { name: 'Привиди / Духи' },
  { name: 'Приховування особистості' },
  { name: 'Раби' },
  { name: 'Ранги сили' },
  { name: 'Регресія' },
  { name: 'Реінкарнація' },
  { name: 'Роботи' },
  { name: 'Розумний ГГ' },
  { name: 'Розумні раси' },
  { name: 'Самураї' },
  { name: 'Середньовіччя' },
  { name: 'Система' },
  { name: 'Спогади з іншого світу' },
  { name: 'Спортивне тіло' },
  { name: 'Стімпанк' },
  { name: 'Супергерої' },
  { name: 'Сучасність' },
  { name: 'Тварини-компаньйони' },
  { name: 'Традиційні ігри' },
  { name: 'Фентезі світ' },
  { name: 'Фермерство' },
  { name: 'Філософія' },
  { name: 'Хікікоморі' },
  { name: 'Холодна зброя' },
  { name: 'Чарівники / маги' },
  { name: 'Шантаж' },
  { name: 'Якудза' },
  { name: 'Яндере' },
]
