/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ModerationRouteRouteImport } from './routes/moderation/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TitleIndexRouteImport } from './routes/title/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as ModerationIndexRouteImport } from './routes/moderation/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as TitleCreateIndexRouteImport } from './routes/title/create/index'
import { Route as TeamCreateIndexRouteImport } from './routes/team/create/index'
import { Route as PeopleCreateIndexRouteImport } from './routes/people/create/index'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as ModerationWorkReviewWorkIdRouteImport } from './routes/moderation/work-review/$workId'
import { Route as ModerationTeamReviewTeamIdRouteImport } from './routes/moderation/team-review/$teamId'
import { Route as ModerationPersonReviewPersonIdRouteImport } from './routes/moderation/person-review/$personId'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRouteRoute = ModerationRouteRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleIndexRoute = TitleIndexRouteImport.update({
  id: '/title/',
  path: '/title/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationIndexRoute = ModerationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModerationRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleCreateIndexRoute = TitleCreateIndexRouteImport.update({
  id: '/title/create/',
  path: '/title/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamCreateIndexRoute = TeamCreateIndexRouteImport.update({
  id: '/team/create/',
  path: '/team/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleCreateIndexRoute = PeopleCreateIndexRouteImport.update({
  id: '/people/create/',
  path: '/people/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ModerationWorkReviewWorkIdRoute =
  ModerationWorkReviewWorkIdRouteImport.update({
    id: '/work-review/$workId',
    path: '/work-review/$workId',
    getParentRoute: () => ModerationRouteRoute,
  } as any)
const ModerationTeamReviewTeamIdRoute =
  ModerationTeamReviewTeamIdRouteImport.update({
    id: '/team-review/$teamId',
    path: '/team-review/$teamId',
    getParentRoute: () => ModerationRouteRoute,
  } as any)
const ModerationPersonReviewPersonIdRoute =
  ModerationPersonReviewPersonIdRouteImport.update({
    id: '/person-review/$personId',
    path: '/person-review/$personId',
    getParentRoute: () => ModerationRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/moderation': typeof ModerationRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/catalog': typeof CatalogRoute
  '/forbidden': typeof ForbiddenRoute
  '/notifications': typeof NotificationsRoute
  '/api/$': typeof ApiSplatRoute
  '/moderation/': typeof ModerationIndexRoute
  '/team/': typeof TeamIndexRoute
  '/title/': typeof TitleIndexRoute
  '/moderation/person-review/$personId': typeof ModerationPersonReviewPersonIdRoute
  '/moderation/team-review/$teamId': typeof ModerationTeamReviewTeamIdRoute
  '/moderation/work-review/$workId': typeof ModerationWorkReviewWorkIdRoute
  '/login/': typeof AuthLoginIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
  '/people/create/': typeof PeopleCreateIndexRoute
  '/team/create/': typeof TeamCreateIndexRoute
  '/title/create/': typeof TitleCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/catalog': typeof CatalogRoute
  '/forbidden': typeof ForbiddenRoute
  '/notifications': typeof NotificationsRoute
  '/api/$': typeof ApiSplatRoute
  '/moderation': typeof ModerationIndexRoute
  '/team': typeof TeamIndexRoute
  '/title': typeof TitleIndexRoute
  '/moderation/person-review/$personId': typeof ModerationPersonReviewPersonIdRoute
  '/moderation/team-review/$teamId': typeof ModerationTeamReviewTeamIdRoute
  '/moderation/work-review/$workId': typeof ModerationWorkReviewWorkIdRoute
  '/login': typeof AuthLoginIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/people/create': typeof PeopleCreateIndexRoute
  '/team/create': typeof TeamCreateIndexRoute
  '/title/create': typeof TitleCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/moderation': typeof ModerationRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/catalog': typeof CatalogRoute
  '/forbidden': typeof ForbiddenRoute
  '/notifications': typeof NotificationsRoute
  '/api/$': typeof ApiSplatRoute
  '/moderation/': typeof ModerationIndexRoute
  '/team/': typeof TeamIndexRoute
  '/title/': typeof TitleIndexRoute
  '/moderation/person-review/$personId': typeof ModerationPersonReviewPersonIdRoute
  '/moderation/team-review/$teamId': typeof ModerationTeamReviewTeamIdRoute
  '/moderation/work-review/$workId': typeof ModerationWorkReviewWorkIdRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/people/create/': typeof PeopleCreateIndexRoute
  '/team/create/': typeof TeamCreateIndexRoute
  '/title/create/': typeof TitleCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/moderation'
    | '/about'
    | '/bookmarks'
    | '/catalog'
    | '/forbidden'
    | '/notifications'
    | '/api/$'
    | '/moderation/'
    | '/team/'
    | '/title/'
    | '/moderation/person-review/$personId'
    | '/moderation/team-review/$teamId'
    | '/moderation/work-review/$workId'
    | '/login/'
    | '/signup/'
    | '/people/create/'
    | '/team/create/'
    | '/title/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/catalog'
    | '/forbidden'
    | '/notifications'
    | '/api/$'
    | '/moderation'
    | '/team'
    | '/title'
    | '/moderation/person-review/$personId'
    | '/moderation/team-review/$teamId'
    | '/moderation/work-review/$workId'
    | '/login'
    | '/signup'
    | '/people/create'
    | '/team/create'
    | '/title/create'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/moderation'
    | '/about'
    | '/bookmarks'
    | '/catalog'
    | '/forbidden'
    | '/notifications'
    | '/api/$'
    | '/moderation/'
    | '/team/'
    | '/title/'
    | '/moderation/person-review/$personId'
    | '/moderation/team-review/$teamId'
    | '/moderation/work-review/$workId'
    | '/_auth/login/'
    | '/_auth/signup/'
    | '/people/create/'
    | '/team/create/'
    | '/title/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ModerationRouteRoute: typeof ModerationRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BookmarksRoute: typeof BookmarksRoute
  CatalogRoute: typeof CatalogRoute
  ForbiddenRoute: typeof ForbiddenRoute
  NotificationsRoute: typeof NotificationsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  TeamIndexRoute: typeof TeamIndexRoute
  TitleIndexRoute: typeof TitleIndexRoute
  PeopleCreateIndexRoute: typeof PeopleCreateIndexRoute
  TeamCreateIndexRoute: typeof TeamCreateIndexRoute
  TitleCreateIndexRoute: typeof TitleCreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/': {
      id: '/title/'
      path: '/title'
      fullPath: '/title/'
      preLoaderRoute: typeof TitleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation/': {
      id: '/moderation/'
      path: '/'
      fullPath: '/moderation/'
      preLoaderRoute: typeof ModerationIndexRouteImport
      parentRoute: typeof ModerationRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/create/': {
      id: '/title/create/'
      path: '/title/create'
      fullPath: '/title/create/'
      preLoaderRoute: typeof TitleCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/create/': {
      id: '/team/create/'
      path: '/team/create'
      fullPath: '/team/create/'
      preLoaderRoute: typeof TeamCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/create/': {
      id: '/people/create/'
      path: '/people/create'
      fullPath: '/people/create/'
      preLoaderRoute: typeof PeopleCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/moderation/work-review/$workId': {
      id: '/moderation/work-review/$workId'
      path: '/work-review/$workId'
      fullPath: '/moderation/work-review/$workId'
      preLoaderRoute: typeof ModerationWorkReviewWorkIdRouteImport
      parentRoute: typeof ModerationRouteRoute
    }
    '/moderation/team-review/$teamId': {
      id: '/moderation/team-review/$teamId'
      path: '/team-review/$teamId'
      fullPath: '/moderation/team-review/$teamId'
      preLoaderRoute: typeof ModerationTeamReviewTeamIdRouteImport
      parentRoute: typeof ModerationRouteRoute
    }
    '/moderation/person-review/$personId': {
      id: '/moderation/person-review/$personId'
      path: '/person-review/$personId'
      fullPath: '/moderation/person-review/$personId'
      preLoaderRoute: typeof ModerationPersonReviewPersonIdRouteImport
      parentRoute: typeof ModerationRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ModerationRouteRouteChildren {
  ModerationIndexRoute: typeof ModerationIndexRoute
  ModerationPersonReviewPersonIdRoute: typeof ModerationPersonReviewPersonIdRoute
  ModerationTeamReviewTeamIdRoute: typeof ModerationTeamReviewTeamIdRoute
  ModerationWorkReviewWorkIdRoute: typeof ModerationWorkReviewWorkIdRoute
}

const ModerationRouteRouteChildren: ModerationRouteRouteChildren = {
  ModerationIndexRoute: ModerationIndexRoute,
  ModerationPersonReviewPersonIdRoute: ModerationPersonReviewPersonIdRoute,
  ModerationTeamReviewTeamIdRoute: ModerationTeamReviewTeamIdRoute,
  ModerationWorkReviewWorkIdRoute: ModerationWorkReviewWorkIdRoute,
}

const ModerationRouteRouteWithChildren = ModerationRouteRoute._addFileChildren(
  ModerationRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ModerationRouteRoute: ModerationRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BookmarksRoute: BookmarksRoute,
  CatalogRoute: CatalogRoute,
  ForbiddenRoute: ForbiddenRoute,
  NotificationsRoute: NotificationsRoute,
  ApiSplatRoute: ApiSplatRoute,
  TeamIndexRoute: TeamIndexRoute,
  TitleIndexRoute: TitleIndexRoute,
  PeopleCreateIndexRoute: PeopleCreateIndexRoute,
  TeamCreateIndexRoute: TeamCreateIndexRoute,
  TitleCreateIndexRoute: TitleCreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
