/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as EmailVerifiedRouteImport } from './routes/email-verified'
import { Route as EmailChangeAcceptedRouteImport } from './routes/email-change-accepted'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ModerationRouteRouteImport } from './routes/moderation/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TitleIndexRouteImport } from './routes/title/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as ModerationIndexRouteImport } from './routes/moderation/index'
import { Route as UserIdRouteImport } from './routes/user/$id'
import { Route as TeamIdRouteImport } from './routes/team/$id'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as UserIdIndexRouteImport } from './routes/user/$id.index'
import { Route as TitleCreateIndexRouteImport } from './routes/title/create/index'
import { Route as TeamCreateIndexRouteImport } from './routes/team/create/index'
import { Route as PeopleCreateIndexRouteImport } from './routes/people/create/index'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as UserIdTeamsRouteImport } from './routes/user/$id.teams'
import { Route as UserIdNotificationsRouteImport } from './routes/user/$id.notifications'
import { Route as UserIdCommentsRouteImport } from './routes/user/$id.comments'
import { Route as UserIdBookmarksRouteImport } from './routes/user/$id.bookmarks'
import { Route as UserIdAboutRouteImport } from './routes/user/$id.about'
import { Route as ModerationTitleReviewTitleIdRouteImport } from './routes/moderation/title-review/$titleId'
import { Route as ModerationTeamReviewTeamIdRouteImport } from './routes/moderation/team-review/$teamId'
import { Route as ModerationPersonReviewPersonIdRouteImport } from './routes/moderation/person-review/$personId'
import { Route as UserIdSettingsRouteRouteImport } from './routes/user/$id_.settings/route'
import { Route as UserIdSettingsIndexRouteImport } from './routes/user/$id_.settings/index'
import { Route as UserIdReviseTeamIndexRouteImport } from './routes/user/$id_.revise-team/index'
import { Route as UserIdSettingsSecurityRouteImport } from './routes/user/$id_.settings/security'
import { Route as UserIdSettingsRootRouteImport } from './routes/user/$id_.settings/root'
import { Route as UserIdSettingsProfileRouteImport } from './routes/user/$id_.settings/profile'
import { Route as UserIdSettingsNotificationsRouteImport } from './routes/user/$id_.settings/notifications'
import { Route as UserIdSettingsDevicesRouteImport } from './routes/user/$id_.settings/devices'
import { Route as UserIdReviseTeamTeamIdRouteImport } from './routes/user/$id_.revise-team/$teamId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifiedRoute = EmailVerifiedRouteImport.update({
  id: '/email-verified',
  path: '/email-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailChangeAcceptedRoute = EmailChangeAcceptedRouteImport.update({
  id: '/email-change-accepted',
  path: '/email-change-accepted',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRouteRoute = ModerationRouteRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleIndexRoute = TitleIndexRouteImport.update({
  id: '/title/',
  path: '/title/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationIndexRoute = ModerationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModerationRouteRoute,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdRoute = TeamIdRouteImport.update({
  id: '/team/$id',
  path: '/team/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdIndexRoute = UserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserIdRoute,
} as any)
const TitleCreateIndexRoute = TitleCreateIndexRouteImport.update({
  id: '/title/create/',
  path: '/title/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamCreateIndexRoute = TeamCreateIndexRouteImport.update({
  id: '/team/create/',
  path: '/team/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleCreateIndexRoute = PeopleCreateIndexRouteImport.update({
  id: '/people/create/',
  path: '/people/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const UserIdTeamsRoute = UserIdTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => UserIdRoute,
} as any)
const UserIdNotificationsRoute = UserIdNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => UserIdRoute,
} as any)
const UserIdCommentsRoute = UserIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => UserIdRoute,
} as any)
const UserIdBookmarksRoute = UserIdBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => UserIdRoute,
} as any)
const UserIdAboutRoute = UserIdAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => UserIdRoute,
} as any)
const ModerationTitleReviewTitleIdRoute =
  ModerationTitleReviewTitleIdRouteImport.update({
    id: '/title-review/$titleId',
    path: '/title-review/$titleId',
    getParentRoute: () => ModerationRouteRoute,
  } as any)
const ModerationTeamReviewTeamIdRoute =
  ModerationTeamReviewTeamIdRouteImport.update({
    id: '/team-review/$teamId',
    path: '/team-review/$teamId',
    getParentRoute: () => ModerationRouteRoute,
  } as any)
const ModerationPersonReviewPersonIdRoute =
  ModerationPersonReviewPersonIdRouteImport.update({
    id: '/person-review/$personId',
    path: '/person-review/$personId',
    getParentRoute: () => ModerationRouteRoute,
  } as any)
const UserIdSettingsRouteRoute = UserIdSettingsRouteRouteImport.update({
  id: '/user/$id_/settings',
  path: '/user/$id/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdSettingsIndexRoute = UserIdSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserIdSettingsRouteRoute,
} as any)
const UserIdReviseTeamIndexRoute = UserIdReviseTeamIndexRouteImport.update({
  id: '/user/$id_/revise-team/',
  path: '/user/$id/revise-team/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdSettingsSecurityRoute = UserIdSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => UserIdSettingsRouteRoute,
} as any)
const UserIdSettingsRootRoute = UserIdSettingsRootRouteImport.update({
  id: '/root',
  path: '/root',
  getParentRoute: () => UserIdSettingsRouteRoute,
} as any)
const UserIdSettingsProfileRoute = UserIdSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserIdSettingsRouteRoute,
} as any)
const UserIdSettingsNotificationsRoute =
  UserIdSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => UserIdSettingsRouteRoute,
  } as any)
const UserIdSettingsDevicesRoute = UserIdSettingsDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => UserIdSettingsRouteRoute,
} as any)
const UserIdReviseTeamTeamIdRoute = UserIdReviseTeamTeamIdRouteImport.update({
  id: '/user/$id_/revise-team/$teamId',
  path: '/user/$id/revise-team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/moderation': typeof ModerationRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/catalog': typeof CatalogRoute
  '/email-change-accepted': typeof EmailChangeAcceptedRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/forbidden': typeof ForbiddenRoute
  '/notifications': typeof NotificationsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/team/$id': typeof TeamIdRoute
  '/user/$id': typeof UserIdRouteWithChildren
  '/moderation/': typeof ModerationIndexRoute
  '/team/': typeof TeamIndexRoute
  '/title/': typeof TitleIndexRoute
  '/user/$id/settings': typeof UserIdSettingsRouteRouteWithChildren
  '/moderation/person-review/$personId': typeof ModerationPersonReviewPersonIdRoute
  '/moderation/team-review/$teamId': typeof ModerationTeamReviewTeamIdRoute
  '/moderation/title-review/$titleId': typeof ModerationTitleReviewTitleIdRoute
  '/user/$id/about': typeof UserIdAboutRoute
  '/user/$id/bookmarks': typeof UserIdBookmarksRoute
  '/user/$id/comments': typeof UserIdCommentsRoute
  '/user/$id/notifications': typeof UserIdNotificationsRoute
  '/user/$id/teams': typeof UserIdTeamsRoute
  '/login/': typeof AuthLoginIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
  '/people/create/': typeof PeopleCreateIndexRoute
  '/team/create/': typeof TeamCreateIndexRoute
  '/title/create/': typeof TitleCreateIndexRoute
  '/user/$id/': typeof UserIdIndexRoute
  '/user/$id/revise-team/$teamId': typeof UserIdReviseTeamTeamIdRoute
  '/user/$id/settings/devices': typeof UserIdSettingsDevicesRoute
  '/user/$id/settings/notifications': typeof UserIdSettingsNotificationsRoute
  '/user/$id/settings/profile': typeof UserIdSettingsProfileRoute
  '/user/$id/settings/root': typeof UserIdSettingsRootRoute
  '/user/$id/settings/security': typeof UserIdSettingsSecurityRoute
  '/user/$id/revise-team/': typeof UserIdReviseTeamIndexRoute
  '/user/$id/settings/': typeof UserIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/catalog': typeof CatalogRoute
  '/email-change-accepted': typeof EmailChangeAcceptedRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/forbidden': typeof ForbiddenRoute
  '/notifications': typeof NotificationsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/team/$id': typeof TeamIdRoute
  '/moderation': typeof ModerationIndexRoute
  '/team': typeof TeamIndexRoute
  '/title': typeof TitleIndexRoute
  '/moderation/person-review/$personId': typeof ModerationPersonReviewPersonIdRoute
  '/moderation/team-review/$teamId': typeof ModerationTeamReviewTeamIdRoute
  '/moderation/title-review/$titleId': typeof ModerationTitleReviewTitleIdRoute
  '/user/$id/about': typeof UserIdAboutRoute
  '/user/$id/bookmarks': typeof UserIdBookmarksRoute
  '/user/$id/comments': typeof UserIdCommentsRoute
  '/user/$id/notifications': typeof UserIdNotificationsRoute
  '/user/$id/teams': typeof UserIdTeamsRoute
  '/login': typeof AuthLoginIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/people/create': typeof PeopleCreateIndexRoute
  '/team/create': typeof TeamCreateIndexRoute
  '/title/create': typeof TitleCreateIndexRoute
  '/user/$id': typeof UserIdIndexRoute
  '/user/$id/revise-team/$teamId': typeof UserIdReviseTeamTeamIdRoute
  '/user/$id/settings/devices': typeof UserIdSettingsDevicesRoute
  '/user/$id/settings/notifications': typeof UserIdSettingsNotificationsRoute
  '/user/$id/settings/profile': typeof UserIdSettingsProfileRoute
  '/user/$id/settings/root': typeof UserIdSettingsRootRoute
  '/user/$id/settings/security': typeof UserIdSettingsSecurityRoute
  '/user/$id/revise-team': typeof UserIdReviseTeamIndexRoute
  '/user/$id/settings': typeof UserIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/moderation': typeof ModerationRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/catalog': typeof CatalogRoute
  '/email-change-accepted': typeof EmailChangeAcceptedRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/forbidden': typeof ForbiddenRoute
  '/notifications': typeof NotificationsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/team/$id': typeof TeamIdRoute
  '/user/$id': typeof UserIdRouteWithChildren
  '/moderation/': typeof ModerationIndexRoute
  '/team/': typeof TeamIndexRoute
  '/title/': typeof TitleIndexRoute
  '/user/$id_/settings': typeof UserIdSettingsRouteRouteWithChildren
  '/moderation/person-review/$personId': typeof ModerationPersonReviewPersonIdRoute
  '/moderation/team-review/$teamId': typeof ModerationTeamReviewTeamIdRoute
  '/moderation/title-review/$titleId': typeof ModerationTitleReviewTitleIdRoute
  '/user/$id/about': typeof UserIdAboutRoute
  '/user/$id/bookmarks': typeof UserIdBookmarksRoute
  '/user/$id/comments': typeof UserIdCommentsRoute
  '/user/$id/notifications': typeof UserIdNotificationsRoute
  '/user/$id/teams': typeof UserIdTeamsRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/people/create/': typeof PeopleCreateIndexRoute
  '/team/create/': typeof TeamCreateIndexRoute
  '/title/create/': typeof TitleCreateIndexRoute
  '/user/$id/': typeof UserIdIndexRoute
  '/user/$id_/revise-team/$teamId': typeof UserIdReviseTeamTeamIdRoute
  '/user/$id_/settings/devices': typeof UserIdSettingsDevicesRoute
  '/user/$id_/settings/notifications': typeof UserIdSettingsNotificationsRoute
  '/user/$id_/settings/profile': typeof UserIdSettingsProfileRoute
  '/user/$id_/settings/root': typeof UserIdSettingsRootRoute
  '/user/$id_/settings/security': typeof UserIdSettingsSecurityRoute
  '/user/$id_/revise-team/': typeof UserIdReviseTeamIndexRoute
  '/user/$id_/settings/': typeof UserIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/moderation'
    | '/about'
    | '/bookmarks'
    | '/catalog'
    | '/email-change-accepted'
    | '/email-verified'
    | '/forbidden'
    | '/notifications'
    | '/verify-email'
    | '/api/$'
    | '/team/$id'
    | '/user/$id'
    | '/moderation/'
    | '/team/'
    | '/title/'
    | '/user/$id/settings'
    | '/moderation/person-review/$personId'
    | '/moderation/team-review/$teamId'
    | '/moderation/title-review/$titleId'
    | '/user/$id/about'
    | '/user/$id/bookmarks'
    | '/user/$id/comments'
    | '/user/$id/notifications'
    | '/user/$id/teams'
    | '/login/'
    | '/signup/'
    | '/people/create/'
    | '/team/create/'
    | '/title/create/'
    | '/user/$id/'
    | '/user/$id/revise-team/$teamId'
    | '/user/$id/settings/devices'
    | '/user/$id/settings/notifications'
    | '/user/$id/settings/profile'
    | '/user/$id/settings/root'
    | '/user/$id/settings/security'
    | '/user/$id/revise-team/'
    | '/user/$id/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/catalog'
    | '/email-change-accepted'
    | '/email-verified'
    | '/forbidden'
    | '/notifications'
    | '/verify-email'
    | '/api/$'
    | '/team/$id'
    | '/moderation'
    | '/team'
    | '/title'
    | '/moderation/person-review/$personId'
    | '/moderation/team-review/$teamId'
    | '/moderation/title-review/$titleId'
    | '/user/$id/about'
    | '/user/$id/bookmarks'
    | '/user/$id/comments'
    | '/user/$id/notifications'
    | '/user/$id/teams'
    | '/login'
    | '/signup'
    | '/people/create'
    | '/team/create'
    | '/title/create'
    | '/user/$id'
    | '/user/$id/revise-team/$teamId'
    | '/user/$id/settings/devices'
    | '/user/$id/settings/notifications'
    | '/user/$id/settings/profile'
    | '/user/$id/settings/root'
    | '/user/$id/settings/security'
    | '/user/$id/revise-team'
    | '/user/$id/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/moderation'
    | '/about'
    | '/bookmarks'
    | '/catalog'
    | '/email-change-accepted'
    | '/email-verified'
    | '/forbidden'
    | '/notifications'
    | '/verify-email'
    | '/api/$'
    | '/team/$id'
    | '/user/$id'
    | '/moderation/'
    | '/team/'
    | '/title/'
    | '/user/$id_/settings'
    | '/moderation/person-review/$personId'
    | '/moderation/team-review/$teamId'
    | '/moderation/title-review/$titleId'
    | '/user/$id/about'
    | '/user/$id/bookmarks'
    | '/user/$id/comments'
    | '/user/$id/notifications'
    | '/user/$id/teams'
    | '/_auth/login/'
    | '/_auth/signup/'
    | '/people/create/'
    | '/team/create/'
    | '/title/create/'
    | '/user/$id/'
    | '/user/$id_/revise-team/$teamId'
    | '/user/$id_/settings/devices'
    | '/user/$id_/settings/notifications'
    | '/user/$id_/settings/profile'
    | '/user/$id_/settings/root'
    | '/user/$id_/settings/security'
    | '/user/$id_/revise-team/'
    | '/user/$id_/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ModerationRouteRoute: typeof ModerationRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BookmarksRoute: typeof BookmarksRoute
  CatalogRoute: typeof CatalogRoute
  EmailChangeAcceptedRoute: typeof EmailChangeAcceptedRoute
  EmailVerifiedRoute: typeof EmailVerifiedRoute
  ForbiddenRoute: typeof ForbiddenRoute
  NotificationsRoute: typeof NotificationsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiSplatRoute: typeof ApiSplatRoute
  TeamIdRoute: typeof TeamIdRoute
  UserIdRoute: typeof UserIdRouteWithChildren
  TeamIndexRoute: typeof TeamIndexRoute
  TitleIndexRoute: typeof TitleIndexRoute
  UserIdSettingsRouteRoute: typeof UserIdSettingsRouteRouteWithChildren
  PeopleCreateIndexRoute: typeof PeopleCreateIndexRoute
  TeamCreateIndexRoute: typeof TeamCreateIndexRoute
  TitleCreateIndexRoute: typeof TitleCreateIndexRoute
  UserIdReviseTeamTeamIdRoute: typeof UserIdReviseTeamTeamIdRoute
  UserIdReviseTeamIndexRoute: typeof UserIdReviseTeamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verified': {
      id: '/email-verified'
      path: '/email-verified'
      fullPath: '/email-verified'
      preLoaderRoute: typeof EmailVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-change-accepted': {
      id: '/email-change-accepted'
      path: '/email-change-accepted'
      fullPath: '/email-change-accepted'
      preLoaderRoute: typeof EmailChangeAcceptedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/': {
      id: '/title/'
      path: '/title'
      fullPath: '/title/'
      preLoaderRoute: typeof TitleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation/': {
      id: '/moderation/'
      path: '/'
      fullPath: '/moderation/'
      preLoaderRoute: typeof ModerationIndexRouteImport
      parentRoute: typeof ModerationRouteRoute
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id': {
      id: '/team/$id'
      path: '/team/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof TeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/': {
      id: '/user/$id/'
      path: '/'
      fullPath: '/user/$id/'
      preLoaderRoute: typeof UserIdIndexRouteImport
      parentRoute: typeof UserIdRoute
    }
    '/title/create/': {
      id: '/title/create/'
      path: '/title/create'
      fullPath: '/title/create/'
      preLoaderRoute: typeof TitleCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/create/': {
      id: '/team/create/'
      path: '/team/create'
      fullPath: '/team/create/'
      preLoaderRoute: typeof TeamCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/create/': {
      id: '/people/create/'
      path: '/people/create'
      fullPath: '/people/create/'
      preLoaderRoute: typeof PeopleCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/user/$id/teams': {
      id: '/user/$id/teams'
      path: '/teams'
      fullPath: '/user/$id/teams'
      preLoaderRoute: typeof UserIdTeamsRouteImport
      parentRoute: typeof UserIdRoute
    }
    '/user/$id/notifications': {
      id: '/user/$id/notifications'
      path: '/notifications'
      fullPath: '/user/$id/notifications'
      preLoaderRoute: typeof UserIdNotificationsRouteImport
      parentRoute: typeof UserIdRoute
    }
    '/user/$id/comments': {
      id: '/user/$id/comments'
      path: '/comments'
      fullPath: '/user/$id/comments'
      preLoaderRoute: typeof UserIdCommentsRouteImport
      parentRoute: typeof UserIdRoute
    }
    '/user/$id/bookmarks': {
      id: '/user/$id/bookmarks'
      path: '/bookmarks'
      fullPath: '/user/$id/bookmarks'
      preLoaderRoute: typeof UserIdBookmarksRouteImport
      parentRoute: typeof UserIdRoute
    }
    '/user/$id/about': {
      id: '/user/$id/about'
      path: '/about'
      fullPath: '/user/$id/about'
      preLoaderRoute: typeof UserIdAboutRouteImport
      parentRoute: typeof UserIdRoute
    }
    '/moderation/title-review/$titleId': {
      id: '/moderation/title-review/$titleId'
      path: '/title-review/$titleId'
      fullPath: '/moderation/title-review/$titleId'
      preLoaderRoute: typeof ModerationTitleReviewTitleIdRouteImport
      parentRoute: typeof ModerationRouteRoute
    }
    '/moderation/team-review/$teamId': {
      id: '/moderation/team-review/$teamId'
      path: '/team-review/$teamId'
      fullPath: '/moderation/team-review/$teamId'
      preLoaderRoute: typeof ModerationTeamReviewTeamIdRouteImport
      parentRoute: typeof ModerationRouteRoute
    }
    '/moderation/person-review/$personId': {
      id: '/moderation/person-review/$personId'
      path: '/person-review/$personId'
      fullPath: '/moderation/person-review/$personId'
      preLoaderRoute: typeof ModerationPersonReviewPersonIdRouteImport
      parentRoute: typeof ModerationRouteRoute
    }
    '/user/$id_/settings': {
      id: '/user/$id_/settings'
      path: '/user/$id/settings'
      fullPath: '/user/$id/settings'
      preLoaderRoute: typeof UserIdSettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id_/settings/': {
      id: '/user/$id_/settings/'
      path: '/'
      fullPath: '/user/$id/settings/'
      preLoaderRoute: typeof UserIdSettingsIndexRouteImport
      parentRoute: typeof UserIdSettingsRouteRoute
    }
    '/user/$id_/revise-team/': {
      id: '/user/$id_/revise-team/'
      path: '/user/$id/revise-team'
      fullPath: '/user/$id/revise-team/'
      preLoaderRoute: typeof UserIdReviseTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id_/settings/security': {
      id: '/user/$id_/settings/security'
      path: '/security'
      fullPath: '/user/$id/settings/security'
      preLoaderRoute: typeof UserIdSettingsSecurityRouteImport
      parentRoute: typeof UserIdSettingsRouteRoute
    }
    '/user/$id_/settings/root': {
      id: '/user/$id_/settings/root'
      path: '/root'
      fullPath: '/user/$id/settings/root'
      preLoaderRoute: typeof UserIdSettingsRootRouteImport
      parentRoute: typeof UserIdSettingsRouteRoute
    }
    '/user/$id_/settings/profile': {
      id: '/user/$id_/settings/profile'
      path: '/profile'
      fullPath: '/user/$id/settings/profile'
      preLoaderRoute: typeof UserIdSettingsProfileRouteImport
      parentRoute: typeof UserIdSettingsRouteRoute
    }
    '/user/$id_/settings/notifications': {
      id: '/user/$id_/settings/notifications'
      path: '/notifications'
      fullPath: '/user/$id/settings/notifications'
      preLoaderRoute: typeof UserIdSettingsNotificationsRouteImport
      parentRoute: typeof UserIdSettingsRouteRoute
    }
    '/user/$id_/settings/devices': {
      id: '/user/$id_/settings/devices'
      path: '/devices'
      fullPath: '/user/$id/settings/devices'
      preLoaderRoute: typeof UserIdSettingsDevicesRouteImport
      parentRoute: typeof UserIdSettingsRouteRoute
    }
    '/user/$id_/revise-team/$teamId': {
      id: '/user/$id_/revise-team/$teamId'
      path: '/user/$id/revise-team/$teamId'
      fullPath: '/user/$id/revise-team/$teamId'
      preLoaderRoute: typeof UserIdReviseTeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ModerationRouteRouteChildren {
  ModerationIndexRoute: typeof ModerationIndexRoute
  ModerationPersonReviewPersonIdRoute: typeof ModerationPersonReviewPersonIdRoute
  ModerationTeamReviewTeamIdRoute: typeof ModerationTeamReviewTeamIdRoute
  ModerationTitleReviewTitleIdRoute: typeof ModerationTitleReviewTitleIdRoute
}

const ModerationRouteRouteChildren: ModerationRouteRouteChildren = {
  ModerationIndexRoute: ModerationIndexRoute,
  ModerationPersonReviewPersonIdRoute: ModerationPersonReviewPersonIdRoute,
  ModerationTeamReviewTeamIdRoute: ModerationTeamReviewTeamIdRoute,
  ModerationTitleReviewTitleIdRoute: ModerationTitleReviewTitleIdRoute,
}

const ModerationRouteRouteWithChildren = ModerationRouteRoute._addFileChildren(
  ModerationRouteRouteChildren,
)

interface UserIdRouteChildren {
  UserIdAboutRoute: typeof UserIdAboutRoute
  UserIdBookmarksRoute: typeof UserIdBookmarksRoute
  UserIdCommentsRoute: typeof UserIdCommentsRoute
  UserIdNotificationsRoute: typeof UserIdNotificationsRoute
  UserIdTeamsRoute: typeof UserIdTeamsRoute
  UserIdIndexRoute: typeof UserIdIndexRoute
}

const UserIdRouteChildren: UserIdRouteChildren = {
  UserIdAboutRoute: UserIdAboutRoute,
  UserIdBookmarksRoute: UserIdBookmarksRoute,
  UserIdCommentsRoute: UserIdCommentsRoute,
  UserIdNotificationsRoute: UserIdNotificationsRoute,
  UserIdTeamsRoute: UserIdTeamsRoute,
  UserIdIndexRoute: UserIdIndexRoute,
}

const UserIdRouteWithChildren =
  UserIdRoute._addFileChildren(UserIdRouteChildren)

interface UserIdSettingsRouteRouteChildren {
  UserIdSettingsDevicesRoute: typeof UserIdSettingsDevicesRoute
  UserIdSettingsNotificationsRoute: typeof UserIdSettingsNotificationsRoute
  UserIdSettingsProfileRoute: typeof UserIdSettingsProfileRoute
  UserIdSettingsRootRoute: typeof UserIdSettingsRootRoute
  UserIdSettingsSecurityRoute: typeof UserIdSettingsSecurityRoute
  UserIdSettingsIndexRoute: typeof UserIdSettingsIndexRoute
}

const UserIdSettingsRouteRouteChildren: UserIdSettingsRouteRouteChildren = {
  UserIdSettingsDevicesRoute: UserIdSettingsDevicesRoute,
  UserIdSettingsNotificationsRoute: UserIdSettingsNotificationsRoute,
  UserIdSettingsProfileRoute: UserIdSettingsProfileRoute,
  UserIdSettingsRootRoute: UserIdSettingsRootRoute,
  UserIdSettingsSecurityRoute: UserIdSettingsSecurityRoute,
  UserIdSettingsIndexRoute: UserIdSettingsIndexRoute,
}

const UserIdSettingsRouteRouteWithChildren =
  UserIdSettingsRouteRoute._addFileChildren(UserIdSettingsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ModerationRouteRoute: ModerationRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BookmarksRoute: BookmarksRoute,
  CatalogRoute: CatalogRoute,
  EmailChangeAcceptedRoute: EmailChangeAcceptedRoute,
  EmailVerifiedRoute: EmailVerifiedRoute,
  ForbiddenRoute: ForbiddenRoute,
  NotificationsRoute: NotificationsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiSplatRoute: ApiSplatRoute,
  TeamIdRoute: TeamIdRoute,
  UserIdRoute: UserIdRouteWithChildren,
  TeamIndexRoute: TeamIndexRoute,
  TitleIndexRoute: TitleIndexRoute,
  UserIdSettingsRouteRoute: UserIdSettingsRouteRouteWithChildren,
  PeopleCreateIndexRoute: PeopleCreateIndexRoute,
  TeamCreateIndexRoute: TeamCreateIndexRoute,
  TitleCreateIndexRoute: TitleCreateIndexRoute,
  UserIdReviseTeamTeamIdRoute: UserIdReviseTeamTeamIdRoute,
  UserIdReviseTeamIndexRoute: UserIdReviseTeamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
